FROM python:3.11-slim

ENV TZ=Asia/Shanghai \
    APP_TIMEZONE=Asia/Shanghai \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -r requirements.txt

COPY . .

EXPOSE 8888

CMD ["python3", "web/app.py"]
